[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    x-robots-tag = "index, follow"